export const FETCH_BRANDS_BEGIN = 'FETCH_BRANDS_BEGIN';
export const FETCH_BRANDS_SUCCEED = 'FETCH_BRANDS_SUCCEED';
export const FETCH_BRANDS_FAILED = 'FETCH_BRANDS_FAILED';

export const FETCH_MODELS_BEGIN = 'FETCH_MODELS_BEGIN';
export const FETCH_MODELS_SUCCEED = 'FETCH_MODELS_SUCCEED';
export const FETCH_MODELS_FAILED = 'FETCH_MODELS_FAILED';

export const FETCH_FUEL_TYPE_BEGIN = 'FETCH_FUEL_TYPE_BEGIN';
export const FETCH_FUEL_TYPE_SUCCEED = 'FETCH_FUEL_TYPE_SUCCEED';
export const FETCH_FUEL_TYPE_FAILED = 'FETCH_FUEL_TYPE_FAILED';

export const HANDLE_BRAND = 'HANDLE_BRAND';
export const HANDLE_MODEL = 'HANDLE_MODEL';
export const HANDLE_FUEL_TYPE = 'HANDLE_FUEL_TYPE';

export const CLEAR_MODELS = 'CLEAR_MODELS';
export const CLEAR_FUEL_TYPES = 'CLEAR_FUEL_TYPES';
